name: Java CI with Maven, Scala and Gatling

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: markhobson/maven-chrome:latest
      options: --network-alias testHost
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Test with Maven and Gatling
      run: mvn gatling:test -Dgatling.simulationClass=computerdatabase.BasicSimulation
    - name: Publish Report
      uses: actions/upload-artifact@v2
      with:
        name: Build Results  
        path: /__w/gatling-maven-plugin-demo/gatling-maven-plugin-demo/target/gatling/
